name: Scrap japanese eshop

# Controls when the action will run.
on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN permissions to write to the repository
    permissions:
      contents: write

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up the newest Python 3 version
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Clone Switch.xml
        run: |
          wget https://www.nintendo.co.jp/data/software/xml/switch.xml
      
      # 5. Run your Python script
      - name: Install libraries
        run: |
          pip install requests

      - name: Run Python script
        run: |
          python extractdata.py

      - name: Upload scrap folder as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: scrap-data
          path: scrap/
          retention-days: 7
