name: Check additional servers

# Controls when the action will run.
on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN permissions to write to the repository
    permissions:
      contents: write

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up the newest Python 3 version
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      
      # 5. Run your Python script
      - name: Install libraries
        run: |
          pip install requests

      - name: Run Python script
        run: |
          python -u alt_region_check.py

      # 6. Commit and push the files from the "output" folder
      - name: Push new files to repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add --ignore-removal output/main_regions_alt.json
          git add --ignore-removal output2/main_regions_alt.json
          git commit -m "Update" || exit 0
          git push
